### ISSUE TITLE
External Link - Icon & New Tab debate

### ISSUE THREAD

**Issue by AlexVanK** [OER-WEB-TEAM/drupal-subtheme--nihod#73]
There has been a lot of talk recently about what the default behavior should be for links that point to a different domain.

## When should the external icon appear?
   - Should it appear when a new tab is about to open?
   - Should it appear when the target domain is different, even though the link does not open on a new tab?
## What does the external icon actually indicate?
   ![image](https://github.com/user-attachments/assets/d8c66930-74c7-4915-9300-9bc39f505eee)
   - Does it indicate the domain is about to change?
   - Does it indicate a new tab is about to open?

**Comment by AlexVanK** [comment]
### Should they open in a new tab?

The team consensus seems to converge to the fact that links should not open automatically in a new tab even if the target domain is different. 
:white_check_mark: This is consistent with the "let the user decide" philosophy. - In fact the Design System does not deviate from this approach.

### When should the external icon appear?
TBD

### What does the external icon actually indicate?
:white_check_mark:  The team consensus seems to converge to interpreting the icon as a change of domain (even though that is not the visual clue that icon seems to give).
:question: So what is the icon to indicate that a new tab is about to open?

**Comment by emsaiz** [comment]
[still looking into this - but these are my thoughts so far]

**Comment by emsaiz** [comment]
_[still looking into this - but these are my thoughts so far]_

### When should the external icon appear?

- **Option A**: External links are handled on a case-by-case basis when deciding whether to open them in the same tab or a new one (default behavior is still open in same tab). This is how we're handling regular links (see Alessio's comment above)! It looks like [USWDS ](https://designsystem.digital.gov/components/link/)_might_ do this as well since they have two external link options in their design system. <img width="430" alt="image" src="https://github.com/user-attachments/assets/a2bea3e1-f9d1-40c5-846c-17b3e3e1e00a">
- **Option B**: because the icon is ambiguous (and people conflate new tab + new domain) we make a rule that all external links open in a new tab. This is what NIAID does! [See their external link guidance](https://digitalpolicy.niaid.nih.gov/policies/external-link-icon#:~:text=External%20links%20should%20open%20in%20a%20new%20window%20or%20tab). 
- **Option C**: external link means new domain and we use wording to indicate whether a link is opening in a new tab. [VA Design System does something similar](https://design.va.gov/content-style-guide/links#linking-to-external-sites). Personally, don't think this will be maintainable or enforceable in the long run AND I can't even find an example of VA doing it on their own site! 
- **Option D**: something else

### Other Findings
- I found this [UK.gov blog post](https://designnotes.blog.gov.uk/2016/11/28/removing-the-external-link-icon-from-gov-uk/) explaining why they decided to remove all external link icons from their site. This isn't an option for our team since [digital.gov requires gov sites to use external link icons](https://digital.gov/resources/required-web-content-and-links/#external-links) but I thought it was interesting to see other teams have the same discussion!
- [UK.gov also posted their team's git-hub discussion](https://github.com/alphagov/govuk_frontend_toolkit/pull/293) on the external link icon. 
- One of their members pointed out that the external link icon can mean three things via google images (which to me highlights the ambiguity in general about this icon): (1) [external link](https://www.google.com/search?q=external+link+icon&sca_esv=9102e70e77a48ac0&sca_upv=1&rlz=1C1GCEA_enUS871US871&udm=2&biw=1162&bih=1154&ei=KffZZtBb4p_k2g_P7JepAQ&ved=0ahUKEwiQlPactqyIAxXiD1kFHU_2JRUQ4dUDCBE&uact=5&oq=external+link+icon&gs_lp=Egxnd3Mtd2l6LXNlcnAiEmV4dGVybmFsIGxpbmsgaWNvbjIKEAAYgAQYQxiKBTIKEAAYgAQYQxiKBTIKEAAYgAQYQxiKBTIKEAAYgAQYQxiKBTIFEAAYgAQyBRAAGIAEMgUQABiABDIFEAAYgAQyBRAAGIAEMgUQABiABEipC1DrBViPCnABeACQAQCYAXegAfADqgEDMy4yuAEDyAEA-AEBmAIGoAKBBJgDAIgGAZIHAzQuMqAH5xs&sclient=gws-wiz-serp) (2) [new window](https://www.google.com/search?q=new+window+icon&sca_esv=9102e70e77a48ac0&sca_upv=1&rlz=1C1GCEA_enUS871US871&udm=2&biw=1162&bih=1154&ei=LffZZpraDNGq5NoPzay_wAQ&ved=0ahUKEwjapPaetqyIAxVRFVkFHU3WD0gQ4dUDCBE&uact=5&oq=new+window+icon&gs_lp=Egxnd3Mtd2l6LXNlcnAiD25ldyB3aW5kb3cgaWNvbjIFEAAYgAQyBRAAGIAEMgUQABiABDIGEAAYBRgeMgYQABgFGB4yBhAAGAgYHjIHEAAYgAQYGDIHEAAYgAQYGDIHEAAYgAQYGDIHEAAYgAQYGEjuL1CsGFiNLnACeACQAQCYAXmgAdwOqgEEMTAuObgBA8gBAPgBAZgCCqACsAbCAgoQABiABBhDGIoFwgIGEAAYBxgewgIQEAAYgAQYsQMYQxiDARiKBcICDRAAGIAEGLEDGEMYigXCAgQQABgDwgIIEAAYBRgHGB7CAggQABgHGAgYHpgDAIgGAZIHAzYuNKAHlGA&sclient=gws-wiz-serp) (3) [share](https://www.google.com/search?q=share++icon&sca_esv=9102e70e77a48ac0&sca_upv=1&rlz=1C1GCEA_enUS871US871&udm=2&biw=1162&bih=1154&ei=P_fZZqOlDcHU5NoPj5_RiQY&ved=0ahUKEwjjwMGntqyIAxVBKlkFHY9PNGEQ4dUDCBE&uact=5&oq=share++icon&gs_lp=Egxnd3Mtd2l6LXNlcnAiC3NoYXJlICBpY29uMg0QABiABBixAxhDGIoFMgoQABiABBhDGIoFMgUQABiABDIFEAAYgAQyBRAAGIAEMgUQABiABDIFEAAYgAQyBRAAGIAEMgUQABiABDIFEAAYgARIjxBQmgtY8g5wAXgAkAEBmAGTAqABgAeqAQUyLjMuMbgBA8gBAPgBAZgCBKAC3ALCAgYQABgHGB7CAgYQABgIGB7CAgcQABiABBgYmAMAiAYBkgcDMy4xoAeEHQ&sclient=gws-wiz-serp)

### Sources 
https://nih-my.sharepoint.com/:x:/g/personal/saizeg_nih_gov/EWA7ZPZ1folMmRsJrynLUmIBTNAR1WoSw0gupQL3IFrbhg?e=OcI8Vb

**Comment by emsaiz** [comment]
### 9/19 Decisions and Next Steps: 

**Decisions**: 
- Decision: external link icons mean NEW DOMAIN not necessarily new window. External links open in same tab except for specific use cases (guide, broken link form, decision tool)
- Decision: add more spacing between list items
- Decision: not taking people to the disclaimer page via icon

**Next Steps:** 
- External icon link clean up: links on the site that have “blank” attribute need to be removed
- Clean up manually added external link icons
- Maybe add tooltip disclaimer for external links
