### ISSUE TITLE
Spinner Component - remove extra spinner colors 

### ISSUE THREAD

**Issue by emsaiz** [OER-WEB-TEAM/drupal-subtheme--nihod#8]
Feel free to disagree...

I think we should show only primary/secondary color spinners and growing loading indicators. I think having all colors gives the impression that they can be any color the customer wants or that there are use cases for using different ones.

I know you are very intentional with what you've done on each page and I don't want to disregard that so let me know what you think!

**Comment by AlexVanK** [comment]
I remember there have been talks about removing the extra colors.
Since the component is so barebone I won't do that for now otherwise we will be left with almost an empty page.

Marking this issue as https://github.com/OER-WEB-TEAM/design-system--drupal-theme/labels/wontfix for now.
Feel free to re-open the issue if other things come up about it. I don't remember the full convo tbh.
